namespace PassKeySample.Api.Models;

/// <summary>
/// Represents a WebAuthn credential (passkey) registered by a user.
/// Stores the cryptographic data needed to verify authentication assertions.
/// </summary>
public class WebAuthnCredential
{
    /// <summary>
    /// The unique identifier of the user who owns this credential.
    /// Typically corresponds to the user's ID in the Identity Provider.
    /// </summary>
    public string UserId { get; set; } = string.Empty;

    /// <summary>
    /// The unique identifier for this credential, generated by the authenticator.
    /// Used to identify which credential to use during authentication.
    /// </summary>
    public byte[] CredentialId { get; set; } = Array.Empty<byte>();

    /// <summary>
    /// The public key associated with this credential, in COSE format.
    /// Used to verify signatures during authentication assertions.
    /// The corresponding private key is securely stored in the user's authenticator.
    /// </summary>
    public byte[] PublicKey { get; set; } = Array.Empty<byte>();

    /// <summary>
    /// The signature counter, incremented by the authenticator on each use.
    /// Used to detect cloned authenticators - if the counter goes backwards,
    /// it may indicate the credential has been compromised.
    /// </summary>
    public uint Counter { get; set; }

    /// <summary>
    /// The timestamp when this credential was first registered.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// The timestamp when this credential was last used for authentication.
    /// Null if the credential has never been used since registration.
    /// </summary>
    public DateTime? LastUsedAt { get; set; }
}
